---
- name: 'Set hostname'
  hostname:
    name: "{{ inventory_hostname }}"
    when: not inventory_hostname|match('(\d{1,3}\.){3}\d{1,3}')
  become: yes

- name: 'Ensure hostname is in /etc/hosts'
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_default_ipv4.address }}.+$"
    line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"
  become: yes

- name: 'Enable ssh after reboot'
  command: 'touch /boot/ssh'
  become: yes

- name: 'Ensure ssh daemon is running'
  command: 'service ssh start'
  become: yes
