---
- name: 'Set hostname'
  hostname:
    name: "{{ inventory_hostname }}"
  become: yes

- name: 'Ensure hostname is in /etc/hosts'
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_default_ipv4.address }}.+$"
    line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"
  become: yes

- name: 'Enable ssh after reboot'
  file:
    path: /boot/ssh
    owner: root
    group: root
    state: touch
  become: yes

- name: 'Ensure ssh daemon is running'
  service: 
    name: ssh
    state: started
    enabled: yes
