---
- name: 'Install w1-gpio driver'
  command: '/sbin/modprobe w1-gpio'
  args:
    creates: '/sys/bus/w1'
  become: yes

- name: 'Install w1-therm driver'
  command: '/sbin/modprobe w1-therm'
  args:
    creates: '/sys/bus/w1'
  become: yes

- name: 'Enable GPIO access'
  lineinfile:
    dest: /boot/config.txt
    regexp: '^dtoverlay=.*'
    line: 'dtoverlay=w1-gpio'

- name: 'Deploy temp_api.py file'
  copy:
    dest: '/usr/local/bin/temp_api.py'
    src: 'files/temp_api.py'
    owner: root
    group: root
    mode: 0755

- name: 'Setup cron watchdog (hack)'
  lineinfile:
    dest: /etc/crontab
    regexp: '.*temp_api.py.*'
    line: '* *     * * *   root      if [ `ps aux | grep -v grep | grep -c /usr/local/bin/temp_api.py` -lt "1" ] ; then /usr/local/bin/temp_api.py & true ; fi'
